# Generated by Django 3.2.2 on 2021-05-14 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='enrollment',
            name='max_seats',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='enrollment_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='enrollments.enrollmenttype'),
        ),
    ]
