# Generated by Django 3.2.2 on 2021-05-14 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0003_enrollmenttype_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='filled_seats',
            field=models.IntegerField(default=0),
        ),
    ]
