# Generated by Django 3.2.2 on 2021-05-14 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('enrollments', '0004_enrollment_filled_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmenttype',
            name='organizer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group'),
        ),
    ]
