# Generated by Django 3.2.3 on 2021-05-15 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0005_enrollmenttype_organizer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollmenttype',
            name='organizer',
        ),
    ]
