# Generated by Django 3.2.3 on 2021-05-17 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0006_remove_enrollmenttype_organizer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
