# Generated by Django 3.2.3 on 2021-05-17 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0007_auto_20210517_1655'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='end_time',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='start_time',
            new_name='start',
        ),
    ]
