# Generated by Django 3.2.3 on 2021-05-18 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0008_auto_20210517_1939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='filled_seats',
            new_name='available_seats',
        ),
    ]
